import mongoose from "mongoose";

const JobSchema = new mongoose.Schema(
  {
    startTime: {
      type: String,
      required: [true, "Please provide startTime"],
      maxlength: 50,
    },
    endTime: {
      type: String,
      required: [true, "Please provide endTime"],
      maxlength: 100,
    },
    day: {
      type: String,
      enum: [
        "Afourer",
        "Agadir",
        "Ait Melloul",
        "Al Hoceima",
        "Assa",
        "Benguerir",
        "Beni Mellal",
        "Berrechid",
        "Casablanca",
        "Deroua",
        "El Gara",
        "El Hajeb",
        "El Jadida",
        "Erfoud",
        "Fes",
        "Fkih Ben Salah",
        "Kenitra",
        "Khemisset",
        "Khouribga",
        "Ksar el Kebir",
        "Larache",
        "Mansour",
        "Marrakesh",
        "Mehediyah",
        "Meknes",
        "Mohammedia",
        "Nador",
        "Ouazzane",
        "Oued Zem",
        "Oujda",
        "Oulad Teima",
        "Rabat",
        "Safi",
        "Sefrou",
        "Settat",
        "Sidi Bennour",
        "Sidi Slimane",
        "Skhirat",
        "Tahala",
        "Tan-Tan",
        "Tangier",
        "Tarfaya",
        "Taza",
        "Temara",
        "Tiflet",
        "Tiznit",
        "Touissite",
      ],
      default: "full-time",
    },
    // createdBy: {
    //   type: mongoose.Types.ObjectId,
    //   ref: "User",
    //   required: [true, "Please provide user"],
    // },
  },
  { timestamps: true }
);

export default mongoose.model("Job", JobSchema);
